name: escrow_mobile
description: A simple application to demonstrate flutter concerpts

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  get: ^4.6.1
  intl: ^0.17.0
  retrofit: ^3.0.1+1
  dio: ^4.0.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  hydrated_bloc: ^8.0.0
  font_awesome_flutter: ^10.1.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.3+1
  flutter_spinkit: ^5.1.0
  keyboard_dismisser: ^3.0.0
  external_path: ^1.0.1
  path_provider:
  shared_preferences: ^2.0.10
  relative_scale: ^2.0.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  retrofit_generator:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

#flutter_icons:
#  image_path_android: 'assets/images/logo_android.png'
#  image_path_ios: 'assets/images/logo_ios.png'
#  ios: true
#  android: true
#
#flutter_native_splash:
#  image: assets/images/tag_line.png
#  color: "#ffffff"
#  android: true
#  ios: true
#  fill: false
